global:
  scrape_interval: 300s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 300s # Evaluate rules every 15 seconds. The default is every 1 minute.

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:5050"]

  - job_name: "neptune_apex"
    static_configs:
      - targets:
        - <APEX IP ADDRESS GOES HERE>
    metrics_path: /metrics/apex
    params:
      auth_module: [default]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: <YOUR LINUX HOSTNAME HERE>:5006

  - job_name: "neptune_fusion"
    static_configs:
      - targets:
        - <FUSION APEX ID GOES HERE>
    metrics_path: /metrics/fusion
    params:
      data_max_age: [300] # Make this the same as your query interval to avoid persistant metrics
    relabel_configs:
      - source_labels: [__param_target]
        target_label: instance
      - source_labels: [__address__]
        target_label: __param_fusion_apex_id

      - target_label: __address__
        replacement: <YOUR LINUX HOSTNAME HERE>:5006