global:
  scrape_interval: 300s
  evaluation_interval: 300s
scrape_configs:
- job_name: prometheus
  static_configs:
  - targets:
    - localhost:9090
- job_name: neptune_apex
  static_configs:
  - targets: null
  metrics_path: /metrics/apex
  params:
    auth_module:
    - default
  relabel_configs:
  - source_labels:
    - __address__
    target_label: __param_target
  - source_labels:
    - __param_target
    target_label: instance
  - target_label: __address__
    replacement: <YOUR LINUX HOSTNAME HERE>:5006
    
- job_name: neptune_fusion
  static_configs:
  - targets: null
  metrics_path: /metrics/fusion
  params:
    data_max_age:
    - 300
  relabel_configs:
  - source_labels:
    - __param_target
    target_label: instance
  - source_labels:
    - __address__
    target_label: __param_fusion_apex_id
  - target_label: __address__
    replacement: <YOUR LINUX HOSTNAME HERE>:5006